server:
   port: 2345
spring:
   profiles:
      active: dev
   application:
      name: my-cloud-config-server
   cloud:
      config:
         server:
            #git: uri:https://github.com/lekhrajprasad/cloud-config-repo
            uri: C:\dev\workspace\cloud-config-repo
eureka:
   client:
      service-url:
         defaultZone: http://localhost:8762/eureka
      healthcheck:
         enabled: true
logging:
   level:
      root: INFO
   pattern:
#org.springframework.cloud: DEBUG
      console: '%-5level [%thread]-${PID} %logger{36}  - %msg%n'
# ----------------
# Orphan comments:
# ----------------
# Was at begin of line:28 :#http://localhost:2345/actuator/